frankframework/frank-doc

.github/workflows/maven-build.yml

The CI will pass when the PR on that project is merged and contains the new version.

Change the IAF repo back to ibissource

---

.editorconfig
frank-doc-frontend/package.json
frank-doc-frontend/src/index.js
frank-doc-frontend/webpack.config.js
frank-doc-frontend/yarn.lock

The fonts weren't imported correctly. Now they're imported explicitly. 
Also set webpack mode to production and use the angularjs-annotate babel plugin, to minify the source, without losing the angular annotations.

Add an import for the font awesome fonts and change mode to production

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/Default.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/Description.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/package-info.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/EnumValue.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/FrankDocModel.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/wrapper/FrankClass.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/wrapper/FrankClassDoclet.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/UtilsFlattenJavaDocLinksTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/feature/DefaultAndDescriptionTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/simple/Start.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/featurepackage/Documented.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/wrapper/variables/Constants.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/wrapper/variables/OtherClass.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/wrapper/variables/Parent.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/wrapper/variables/alt/ClassInOtherPackage.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/VariablesTest.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/simple.json
frank-doc-doclet/src/test/resources/doc/examplesExpected/simple.xsd

I may not have tested all corner cases

Resolve values

---

frank-doc-frontend/package.json
frank-doc-frontend/src/app/pipes/javadoc.pipe.spec.ts
frank-doc-frontend/src/app/pipes/javadoc.pipe.ts
frank-doc-frontend/src/index.html

Removed base element from index so that everything loads relatively to the frank!doc url no matter the application context

fix frankdoc not loading in F!F due to base url

---

frank-doc-frontend/src/environments/environment.ts

update production env file to hopefully load the frankdoc.json & FrankConfig.xsd

Fix for console environment

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/feature/DefaultAndDescriptionTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/feature/ExtendsClassJavadocTest.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/simple.json
frank-doc-doclet/src/test/resources/doc/examplesExpected/simple.xsd
frank-doc-doclet/src/test/resources/doc/examplesExpected/valueSubs.json
frank-doc-doclet/src/test/resources/doc/examplesExpected/valueSubs.xsd

Highlight literal text using code blocks

---

.github/workflows/validConfig.xml

Change FixedResultPipe to EchoPipe to reflect changes to the framework language

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/FrankDocJsonFactory.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/Forward.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/FrankElement.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/wrapper/FrankAnnotationDoclet.java
frank-doc-doclet/src/test/java/org/frankframework/doc/Forward.java
frank-doc-doclet/src/test/java/org/frankframework/doc/Forwards.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/forwards/Master.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/forwards/Parent.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/forwards.json

`frankdoc.json` of my branch, so you don't have to build locally :)
[frankdoc.json](https://github.com/user-attachments/files/16945176/frankdoc.json)
Closes https://github.com/frankframework/frank-doc/issues/203

Add java annotation, which mimics the behavior of ff.forward, so it can be replaced.

---

.github/workflows/maven-build.yml
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/UtilsTest.java

Closes #223 
This allows reviewers to easily compare changes to previous versions.

Automatically upload the FrankDoc json and xsd

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/simple/Start.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/simple.json
frank-doc-doclet/src/test/resources/doc/examplesExpected/simple.xsd

Surround a literal value with backticks.

---

frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/featurepackage/DocumentedParent.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/documented.json

Closes https://github.com/frankframework/frank-doc/issues/233

Create tests for {@literal ..}.

---

.editorconfig
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/FrankDocXsdFactory.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/IntegrationWithLogTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/integration/HierarchyTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/hierarchy/AbstractParameter.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/hierarchy/IParameter.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/hierarchy/IPipe.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/hierarchy/JwtPipe.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/hierarchy/NumberParameter.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/hierarchy/Parameter.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/hierarchy/Start.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/configChildren2.xsd
frank-doc-doclet/src/test/resources/doc/examplesExpected/hierarchy.xsd
frank-doc-doclet/src/test/resources/doc/examplesExpected/testPluralConflictDefaultOption.xsd
frank-doc-doclet/src/test/resources/doc/examplesExpected/withDefault.xsd
frank-doc-doclet/src/test/resources/doc/hierarchy-digester-rules.xml
frank-doc-doclet/src/test/resources/doc/testConfigs/testExotic.xml

Closes https://github.com/frankframework/frankframework/issues/7682

Add an xs:anyAttribute when there is a name conflict between interface and concrete class

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/XsdVersion.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/wrapper/FrankMethodDocletBase.java

Replace a few warn logs with info

---

frank-doc-frontend/src/app/views/index/index.component.html

Replace dummy text with more descriptive info on index page

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/FrankDocXsdFactory.java

Closes https://github.com/frankframework/frank-doc/issues/262

Revert changes from 242 for compatibility mode

---

frank-doc-frontend/src/app/views/details/details-element/details-element.component.html
frank-doc-frontend/src/app/views/details/details-element/details-element.component.scss
frank-doc-frontend/src/app/views/details/details-element/details-element.component.ts
frank-doc-frontend/src/app/views/details/details-search/details-search.component.ts
frank-doc-frontend/src/app/views/home/home.component.ts
frank-doc-frontend/src/app/views/index/index.component.html
frank-doc-frontend/src/app/views/index/index.component.scss
frank-doc-frontend/src/app/views/index/index.component.ts

Deprecated attributes have a title containing the deprecation description and since information if available

Add deprecation indicators to deprecated elements & attributes

---

frank-doc-frontend/package.json
frank-doc-frontend/src/app/app.component.ts
frank-doc-frontend/src/app/app.routes.ts
frank-doc-frontend/src/app/app.service.ts
frank-doc-frontend/src/app/search-query-params.service.spec.ts
frank-doc-frontend/src/app/search-query-params.service.ts
frank-doc-frontend/src/app/views/details/details-element/details-element.component.html
frank-doc-frontend/src/app/views/details/details-element/details-element.component.ts
frank-doc-frontend/src/app/views/home/home-filters/home-filters.component.ts
frank-doc-frontend/src/app/views/home/home.component.html
frank-doc-frontend/src/app/views/home/home.component.scss
frank-doc-frontend/src/app/views/home/home.component.spec.ts
frank-doc-frontend/src/app/views/home/home.component.ts

This makes sure the back button will save what search query is used and which filters were selected

Save search & filter information in url

---

frank-doc-frontend/src/app/app.constants.ts
frank-doc-frontend/src/app/app.routes.ts
frank-doc-frontend/src/app/components/header/header.component.html
frank-doc-frontend/src/app/components/javadoc-transform.directive.ts
frank-doc-frontend/src/app/components/name-wbr.pipe.ts
frank-doc-frontend/src/app/frankdoc.types.ts
frank-doc-frontend/src/app/views/properties/properties.component.html
frank-doc-frontend/src/app/views/properties/properties.component.scss
frank-doc-frontend/src/app/views/properties/properties.component.spec.ts
frank-doc-frontend/src/app/views/properties/properties.component.ts

http://localhost:4200/#/appconstants

Add AppConstants overview

---

frank-doc-frontend/src/app/app.constants.ts
frank-doc-frontend/src/app/app.service.ts
frank-doc-frontend/src/app/views/details/details-element/details-element.component.html
frank-doc-frontend/src/app/views/details/details-element/details-element.component.ts
frank-doc-frontend/src/app/views/index/index.component.html
frank-doc-frontend/src/app/views/index/index.component.ts

New label colours based on filter group names:

Replace filterColour list with generated distinct colours for filter groups

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/FrankDocJsonFactory.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/CredentialProvider.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/FrankDocModel.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/wrapper/FrankClassRepository.java
frank-doc-doclet/src/test/java/org/frankframework/credentialprovider/ICredentialFactory.java
frank-doc-doclet/src/test/java/org/frankframework/credentialprovider/NoJavadocCredentialFactory.java
frank-doc-doclet/src/test/java/org/frankframework/credentialprovider/TestCredentialFactory.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/integration/CredentialProviderTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/dummy/Dummy.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/credentialProvider.json

Close #312 
CI is fixed in #314

Add credential providers

---

frank-doc-frontend/src/app/views/details/details-element/details-element.component.html
frank-doc-frontend/src/app/views/details/details-element/details-element.component.ts

This is a temporary fix, see [this issue](https://github.com/frankframework/frank-doc/issues/348)

Inherit missing forwards from parents

---

frank-doc-frontend/package.json
frank-doc-frontend/pnpm-lock.yaml

Updated Angular Components to fix buttons resizing when clicked and make search text smaller.

Update Angular Components lib

---

frank-doc-frontend/src/styles.scss

Fix height for sidebars in small pages

---

frank-doc-frontend/src/app/components/header/header.component.html
frank-doc-frontend/src/app/components/header/header.component.ts
frank-doc-frontend/src/app/view-title-strategy.ts
frank-doc-frontend/src/app/views/details/details-element/details-element.component.ts
frank-doc-frontend/src/app/views/details/details-search/details-search.component.html
frank-doc-frontend/src/app/views/details/details.component.ts
frank-doc-frontend/src/environments/environment.development.ts
frank-doc-frontend/src/environments/environment.ts

And some small changes / improvements

Fix ToC not updating properly on element change
