frankframework/frank-doc

src/main/java/org/frankframework/frankdoc/model/FrankAttribute.java
src/main/java/org/frankframework/frankdoc/model/FrankDocModel.java
src/test/java/org/frankframework/frankdoc/model/FrankDocModelTest.java
src/test/java/org/frankframework/frankdoc/testtarget/ibisdocref/ParentTarget.java
src/test/java/org/frankframework/frankdoc/testtarget/ibisdocref/Referrer.java

This is a very basic implementation. I have the following ideas to extend it:
* If there an attribute has a description and ff.refer, then the description found via ff.refer is overwritten by JavaDoc on the method. We may combine the two instead of choosing one. In that case: do we add a separator like `<p>`?
* There are many sources (IbisDoc, IbisDocRef, JavaDoc, ff.refer) of default values and descriptions. There are no warnings if these conflict. Shall I add such warnings?
* Shall I add that ff.mandatory or ff.noAttribute on the referred method are applied for the attribute?

Introduce tag ff.refer to replace IbisDocRef

---

frank-doc-frontend/src/app/pipes/as-text.pipe.ts

fix as-text pipe transformLink having wrong context for "this"

Fix inheritance merged attributes not being shown at all when enabled

---

.github/workflows/angular-ci.yml
.github/workflows/maven-build.yml
frank-doc-doclet/pom.xml
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/doclet/Doclet.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/doclet/DocletBuilder.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/FrankDocModel.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/model/ConfigChildSetterDescriptorTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/model/FrankDocModelTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testdoclet/EasyDoclet.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/EasyDocletTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/FilteringInterfaceImplementationsTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/FilteringSuperclassTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/TestUtil.java
frank-doc-frontend/pom.xml
pom.xml

Refactored mechanism how the EasyDoclet in the unittests was used. Now it uses less internals of the JVM, but uses the `Start` class of the Javadoc tools. The same tools are used by the Javadoc binary itself, so it is more future proof. 
Secondly, bumped a lot of plugins used and deps were available.

Move to Java 17 and higher

---

frank-doc-doclet/pom.xml
pom.xml

Merges the configurations of the source and javadoc plugin, and enable them by default (via the parent pom).

Merge poms

---

frank-doc-doclet/pom.xml
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/DocWriterNewAndJsonGenerationExamplesTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/model/FrankDocModelTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/doclet/Child.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/sameEnum/only/once/Master.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/reflect/FrankAttributeTarget.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/FrankClass2Test.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/FrankClassTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/FrankMethodTest.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/enumOnlyOnce.xsd

The output of a run with the current code in the PR, on the `ApiListener.setMethods(HttpMethod... methods)` is:
```
<xs:attribute name="methods">
<xs:annotation>
<xs:documentation>HTTP method(s) to listen to, separated by comma Default: GET</xs:documentation>
</xs:annotation>
<xs:simpleType>
<xs:union memberTypes="HttpMethodAttributeValuesType variableRef" />
</xs:simpleType>
</xs:attribute>
```
I have a little doubt if this is okay 'enough'. The Enum is a list, but actually we can put in multiple values as a String. So, perhaps I should change it to type `xs:string` when a VarArg is supplied?

Support var-args parameter on setters too

---

frank-doc-doclet/pom.xml
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/Default.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/Description.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/EnumValue.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/FrankElement.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/UtilsTest.java

Closes #196 
`FrankSender` and `FixedResultPipe` both contain quite a few problems related to javadoc tags. They are great for testing my changes.
**Changes:**
- {@code ..} blocks do not render correctly
- Having a `{}` tag inside a javadoc tag is not possible
- {@literal ..} Is not supported
I will implement @inheritdoc in another PR, due to it's complexity.

Properly display Javadoc code blocks

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/ConfigChildSetterDescriptor.java

Closes https://github.com/frankframework/frankframework/issues/1601
Requires the accompying PR for the FF to be merged first.

Disallow the use of registerXyz digester methods

---

frank-doc-frontend/src/app/app.config.ts

Automatic scroll to top on new navigation but keeps previous scroll position in memory for when the user uses the 'back' button

Enable scrollPositionRestoration for router navigation

---

frank-doc-frontend/src/app/views/home/home-filters/home-filters.component.html
frank-doc-frontend/src/app/views/home/home-filters/home-filters.component.scss
frank-doc-frontend/src/styles.scss

Consistent padding on the options compared to before, pointer cursor and hover background colour
On hover:
On clicked:

Add cursor effects to filter menu

---

frank-doc-frontend/package.json
frank-doc-frontend/pnpm-lock.yaml

Hopefully upgrading PNPM will fix the jenkins builds.
I had to put a lot of effort in to get the version to be upgraded without it breaking corepack.
At first it gave something about a wrong version hash or something similar, but got it working after I tried to disable and remove corepack from npm, update node to the latest LTS and then enable corepack again and use that to upgrade PNPM.

Upgrade pnpm to 10.5.2

---

frank-doc-frontend/src/app/frankdoc.types.ts
frank-doc-frontend/src/app/views/details/details-element/details-element.component.html
frank-doc-frontend/src/app/views/details/details-element/details-element.component.scss
frank-doc-frontend/src/app/views/details/details-element/details-element.component.ts

This PR adds extra notes to the details page (the deprecation warning was already there)

Show notes / warnings on the details page

---

.github/workflows/test-doclet.yml
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/FrankElement.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/see/See.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/see.json

Closes #314 
actions/upload-artifact updated because of: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Generate quicklinks when the a tag has text behind the link

---

frank-doc-frontend/src/app/components/javadoc-transform.directive.ts
frank-doc-frontend/src/app/views/details/details-element/details-element.component.html
frank-doc-frontend/src/app/views/details/details-element/details-element.component.scss
frank-doc-frontend/src/styles.scss

This PR lets the description show with preformatted text in order to fix both #79 and #333, however the use of both newline characters and `<p>` & `<br>` elements adds a lot more white space then possible expected.
This may be fixed by updating the javadoc or deciding to remove newline characters in the frontend which will negatively impact the solution for #333

Fix preformatted text in element descriptions

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/Utils.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/UtilsTest.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/wrapper/TestUtil.java

Adds new functionality to Utils for consistent JSON ordering and comparison
This pull request introduces the jsonOrder method in the Utils class to ensure consistent ordering of JSON object keys. It also updates the TestUtil.assertJsonEqual method to ignore key order and formatting differences when comparing JSON objects. These changes resolve issues with tests failing due to variations in key order or formatting, ensuring tests compare the actual data rather than serialization differences.

Update assertJsonEqual to ignore element order

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/Description.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/feature/Notes.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/inheritdoc/Child.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/inheritdoc/Parent.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/inheritdoc/ParentOfParent.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/notes/Note.java
frank-doc-doclet/src/test/resources/doc/examplesExpected/category.json

These changes allow for `inheritClassDoc` to be used in class docs, instead of inheritDoc
NOTE: currently static variable `INHERIT_CLASS_DOC_TAG` within the `Description` class has a trailing space within the brackets because this tag is returned as such when processing. I am unsure why this happens, but the trailing space seems to work.

Rename `inheritDoc` to `inheritClassDoc` when used above a class

---

frank-doc-frontend/src/app/views/details/details-element/details-element.component.html
frank-doc-frontend/src/app/views/details/details-element/details-element.component.scss
frank-doc-frontend/src/app/views/details/details-element/details-element.component.ts
frank-doc-frontend/src/styles.scss

This pull request refactors and improves the structure, styling, and readability of the details page. 
The biggest change is the table layout. The columns with a lot of text have been changes to extra rows. Related rows are grouped together. 
The columns now have a fixed width for a cleaner look.
The enumerations (or options) are now shown inline, and in a list when they have a description.
When no attributes are present, the tables will be hidden.

Improve attribute and other table layouts

---

frank-doc-frontend/src/app/views/properties/properties.component.html

Set width and height to a correct value and made it a little bit bigger since 16px looked too small to me

Fix properties flags icon throwing errors

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/model/ParsedJavaDocTag.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/wrapper/FrankClass.java
frank-doc-doclet/src/main/java/org/frankframework/frankdoc/wrapper/FrankDocletUtils.java
frank-doc-doclet/src/test/java/org/frankframework/frankdoc/testtarget/examples/parameters/Child1.java

Parser now checks for tabs and spaces as delimiter to improve formatting.

add tabs as tag delimiter

---

frank-doc-doclet/src/main/java/org/frankframework/frankdoc/properties/PropertyParser.java

Limits the splitting of property lines to two

limit amount of split actions to two, to avoid splitting of the property value

---

frank-doc-frontend/src/app/components/collapse.directive.ts

This pull request updates the `CollapseDirective` directive to improve how the initial state of collapsible elements is set. The main change involves replacing the `updateState` method call with a new `setInitialState` method, which ensures proper initialization of the collapsed state.
Changes to `CollapseDirective`:
* Replaced the `updateState` method with a new `setInitialState` method in the `ngAfterViewInit` lifecycle hook to handle the initial state of collapsible elements. (`frank-doc-frontend/src/app/components/collapse.directive.ts`, [frank-doc-frontend/src/app/components/collapse.directive.tsL17-R17](diffhunk://#diff-d7153aa8f2b6bce3dbfb00cff86b1f7a31473ad7f3e924f8dbec996a46197cbbL17-R17))
* Added the `setInitialState` method, which checks if the element is collapsed and applies …

Remove inital expand animation for collapsable menus

---

frank-doc-frontend/src/app/views/credential-providers/credential-providers.component.html
frank-doc-frontend/src/app/views/details/details-search/details-search.component.scss
frank-doc-frontend/src/app/views/details/details.component.html
frank-doc-frontend/src/app/views/index/index.component.html
frank-doc-frontend/src/app/views/properties/properties.component.html
frank-doc-frontend/src/app/views/servlet-authenticators/servlet-authenticators.component.html
frank-doc-frontend/src/styles.scss

Side menus for details, index & properties page are now sticky
I did however not manage to make element component tables have sticky headers

Make side navigation menus sticky
